<?php

namespace Database\Seeders;

use App\Models\HeaderTheme;
use Illuminate\Database\Seeder;

class HeaderThemeSeeder extends Seeder
{
    public function run(): void
    {
        $themes = [
            [
                'slug' => 'sevgililer-gunu',
                'name' => ['tr' => 'Sevgililer Günü', 'en' => 'Valentine\'s Day', 'ku' => 'Roja Evînê'],
                'theme_type' => HeaderTheme::TYPE_FIXED,
                'month' => 2,
                'day' => 14,
                'priority' => 180,
                'banner_message' => ['tr' => '14 Şubat için sınırlı butik seçki', 'en' => 'Limited Valentine boutique edit', 'ku' => 'Bijarteya evînê ya sînorkirî'],
                'headline' => ['tr' => 'Romantik buketler ve çikolata kutuları hazır.', 'en' => 'Romantic bouquets and chocolate boxes are ready.', 'ku' => 'Buketên evînî û qutiyên çîkolatayê amade ne.'],
                'subline' => ['tr' => 'Aynı gün teslim edilebilen güller, zarif aranjmanlar ve tatlı sürprizlerle hediyenizi bugünden planlayın.', 'en' => 'Plan your gift with same-day roses, refined arrangements and sweet surprises.', 'ku' => 'Diyariya xwe bi gul, aranjmanên zarif û surprîzên şîrîn amade bikin.'],
                'cta_label' => ['tr' => 'Sevgililer koleksiyonunu keşfet', 'en' => 'Explore Valentine gifts', 'ku' => 'Bijarteya evînê bibîne'],
                'special_occasion_slug' => 'sevgililer-gunu',
                'style_variant' => 'romantic',
                'illustration_mode' => 'inline_svg',
                'illustration_asset' => 'hearts',
                'decor_intensity' => 'medium',
            ],
            [
                'slug' => 'kadinlar-gunu',
                'name' => ['tr' => 'Dünya Kadınlar Günü', 'en' => 'International Women\'s Day', 'ku' => 'Roja Jinan a Cîhanê'],
                'theme_type' => HeaderTheme::TYPE_FIXED,
                'month' => 3,
                'day' => 8,
                'priority' => 170,
                'banner_message' => ['tr' => 'Kadınlar Günü', 'en' => 'Women\'s Day edit', 'ku' => 'Roja Jinan'],
                'headline' => ['tr' => 'Güçlü, zarif ve anlamlı bir kutlama.', 'en' => 'A confident, elegant and meaningful celebration.', 'ku' => 'Pîrozbahiyeke xurt, zarif û watedar.'],
                'subline' => ['tr' => 'Mimoza sıcaklığında çiçekler ve özenli hediye alternatifleriyle günü daha görünür kılın.', 'en' => 'Make the day visible with warm florals and thoughtful gift alternatives.', 'ku' => 'Bi kulîlkên germ û diyariyên bi baldarî rojê xweş bikin.'],
                'cta_label' => ['tr' => 'Seçkiyi gör', 'en' => 'See edit', 'ku' => 'Bibîne'],
                'special_occasion_slug' => 'kadinlar-gunu',
                'style_variant' => 'warm',
                'illustration_mode' => 'inline_svg',
                'illustration_asset' => 'mimosa',
                'decor_intensity' => 'medium',
            ],
            [
                'slug' => 'tip-bayrami',
                'name' => ['tr' => 'Tıp Bayramı', 'en' => 'Medical Day', 'ku' => 'Cejna Tibbê'],
                'theme_type' => HeaderTheme::TYPE_FIXED,
                'month' => 3,
                'day' => 14,
                'priority' => 160,
                'banner_message' => ['tr' => 'Tıp Bayramı', 'en' => 'Medical Day gifts', 'ku' => 'Cejna Tibbê'],
                'headline' => ['tr' => 'Sağlık emekçilerine ferah bir teşekkür gönderin.', 'en' => 'Send a graceful thank-you to healthcare professionals.', 'ku' => 'Spasiya xwe ji karmendên tenduristiyê re bi zarafet bişînin.'],
                'subline' => ['tr' => 'Temiz tonlu çiçekler, sade kutular ve not kartlarıyla içten bir kutlama hazırlayın.', 'en' => 'Prepare a sincere celebration with fresh florals, refined boxes and note cards.', 'ku' => 'Bi kulîlkên zelal, qutiyên sade û kartên peyamê pîrozbahiyek amade bikin.'],
                'cta_label' => ['tr' => 'Hediyeleri gör', 'en' => 'See gifts', 'ku' => 'Bibîne'],
                'special_occasion_slug' => 'tip-bayrami',
                'style_variant' => 'fresh',
                'illustration_mode' => 'inline_svg',
                'illustration_asset' => 'medical',
                'decor_intensity' => 'soft',
            ],
            [
                'slug' => 'anneler-gunu',
                'name' => ['tr' => 'Anneler Günü', 'en' => 'Mother\'s Day', 'ku' => 'Roja Dayikan'],
                'theme_type' => HeaderTheme::TYPE_NTH_WEEKDAY,
                'month' => 5,
                'weekday' => 0,
                'nth_week' => 2,
                'priority' => 175,
                'banner_message' => ['tr' => 'Anneler hediyeleri', 'en' => 'Mother\'s Day gifts', 'ku' => 'Diyariyên dayikan'],
                'headline' => ['tr' => 'Annenize zarif buketler ve tatlı sürprizler hazırlayın.', 'en' => 'Prepare elegant bouquets and sweet surprises for your mother.', 'ku' => 'Ji dayika xwe re buketên zarif û surprîzên şîrîn amade bikin.'],
                'subline' => ['tr' => 'Pudra tonlu çiçekler, sıcak notlar ve aynı gün teslim seçenekleriyle duygunuzu net anlatın.', 'en' => 'Share your feeling with soft florals, warm notes and same-day delivery options.', 'ku' => 'Bi kulîlkên nerm, peyamên germ û radestkirina heman rojê hestên xwe bibêjin.'],
                'cta_label' => ['tr' => 'Hediyeleri gör', 'en' => 'See gifts', 'ku' => 'Bibîne'],
                'special_occasion_slug' => 'anneler-gunu',
                'style_variant' => 'warm',
                'illustration_mode' => 'inline_svg',
                'illustration_asset' => 'mother',
                'decor_intensity' => 'medium',
            ],
            [
                'slug' => 'babalar-gunu',
                'name' => ['tr' => 'Babalar Günü', 'en' => 'Father\'s Day', 'ku' => 'Roja Bavikan'],
                'theme_type' => HeaderTheme::TYPE_NTH_WEEKDAY,
                'month' => 6,
                'weekday' => 0,
                'nth_week' => 3,
                'priority' => 165,
                'banner_message' => ['tr' => 'Babalar seçkisi', 'en' => 'Father\'s Day edit', 'ku' => 'Bijarteya bavikan'],
                'headline' => ['tr' => 'Sade, güçlü ve şık hediye alternatifleri.', 'en' => 'Simple, confident and polished gift alternatives.', 'ku' => 'Diyariyên sade, xurt û şık.'],
                'subline' => ['tr' => 'Çikolata kutuları, karakterli bitkiler ve rafine aranjmanlarla net bir teşekkür gönderin.', 'en' => 'Send a clear thank-you with chocolate boxes, distinctive plants and refined arrangements.', 'ku' => 'Bi qutiyên çîkolatayê, nebatan û aranjmanên rafîne spasiyek bişînin.'],
                'cta_label' => ['tr' => 'Seçkiyi gör', 'en' => 'See edit', 'ku' => 'Bibîne'],
                'special_occasion_slug' => 'babalar-gunu',
                'style_variant' => 'tailored',
                'illustration_mode' => 'inline_svg',
                'illustration_asset' => 'tailored',
                'decor_intensity' => 'soft',
            ],
            [
                'slug' => 'ogretmenler-gunu',
                'name' => ['tr' => 'Öğretmenler Günü', 'en' => 'Teachers\' Day', 'ku' => 'Roja Mamosteyan'],
                'theme_type' => HeaderTheme::TYPE_FIXED,
                'month' => 11,
                'day' => 24,
                'priority' => 155,
                'banner_message' => ['tr' => 'Öğretmen hediyeleri', 'en' => 'Teacher gifts', 'ku' => 'Diyariyên mamosteyan'],
                'headline' => ['tr' => 'Teşekkürünüzü zarif bir buketle anlatın.', 'en' => 'Say thank you with an elegant bouquet.', 'ku' => 'Spasiya xwe bi buketek zarif bibêjin.'],
                'subline' => ['tr' => 'Not kartı, canlı çiçek ve butik çikolata seçenekleriyle öğretmeninize anlamlı bir jest yapın.', 'en' => 'Make a meaningful gesture with note cards, fresh flowers and boutique chocolates.', 'ku' => 'Bi kart, kulîlk û çîkolatayên butik jestek watedar bikin.'],
                'cta_label' => ['tr' => 'Hediyeleri gör', 'en' => 'See gifts', 'ku' => 'Bibîne'],
                'special_occasion_slug' => 'ogretmenler-gunu',
                'style_variant' => 'tribute',
                'illustration_mode' => 'inline_svg',
                'illustration_asset' => 'teacher',
                'decor_intensity' => 'medium',
            ],
            [
                'slug' => 'ramazan-bayrami',
                'name' => ['tr' => 'Ramazan Bayramı', 'en' => 'Eid al-Fitr', 'ku' => 'Cejna Ramazanê'],
                'theme_type' => HeaderTheme::TYPE_RANGE,
                'starts_at' => '2026-03-20',
                'ends_at' => '2026-03-22',
                'priority' => 190,
                'banner_message' => ['tr' => 'Bayram vitrini', 'en' => 'Eid gift edit', 'ku' => 'Vitrîna cejnê'],
                'headline' => ['tr' => 'Bayram hediyeleri zarif bir seçkide toplandı.', 'en' => 'Eid gifts are gathered in an elevated edit.', 'ku' => 'Diyariyên cejnê di bijarteyeke zarif de ne.'],
                'subline' => ['tr' => 'Işıltılı çikolata kutuları, taze çiçekler ve paylaşım odaklı hediyelerle bayramlaşmayı tamamlayın.', 'en' => 'Complete your Eid visits with bright chocolate boxes, fresh flowers and sharing-led gifts.', 'ku' => 'Bi qutiyên çîkolatayê, kulîlkên taze û diyariyên parvekirinê cejnê xweş bikin.'],
                'cta_label' => ['tr' => 'İncele', 'en' => 'Browse', 'ku' => 'Bibîne'],
                'special_occasion_slug' => 'ramazan-bayrami',
                'style_variant' => 'bayram',
                'illustration_mode' => 'inline_svg',
                'illustration_asset' => 'eid-lantern',
                'decor_intensity' => 'medium',
            ],
            [
                'slug' => 'kurban-bayrami',
                'name' => ['tr' => 'Kurban Bayramı', 'en' => 'Eid al-Adha', 'ku' => 'Cejna Qurbanê'],
                'theme_type' => HeaderTheme::TYPE_RANGE,
                'starts_at' => '2026-05-27',
                'ends_at' => '2026-05-30',
                'priority' => 188,
                'banner_message' => ['tr' => 'Bayram seçkisi', 'en' => 'Eid edit', 'ku' => 'Bijarteya cejnê'],
                'headline' => ['tr' => 'Bayram sofralarına çiçek ve çikolata eşlik etsin.', 'en' => 'Let flowers and chocolates join your Eid gatherings.', 'ku' => 'Bila kulîlk û çîkolata bi cejna we re bin.'],
                'subline' => ['tr' => 'Sıcak tonlu aranjmanlar ve ikramlık çikolatalarla ziyaretlerinize özenli bir dokunuş ekleyin.', 'en' => 'Add a thoughtful touch with warm arrangements and giftable chocolates.', 'ku' => 'Bi aranjmanên germ û çîkolatayên diyariyê destekek xweş lê zêde bikin.'],
                'cta_label' => ['tr' => 'Gör', 'en' => 'See', 'ku' => 'Bibîne'],
                'special_occasion_slug' => 'kurban-bayrami',
                'style_variant' => 'bayram',
                'illustration_mode' => 'inline_svg',
                'illustration_asset' => 'eid-crescent',
                'decor_intensity' => 'medium',
            ],
            [
                'slug' => 'yilbasi',
                'name' => ['tr' => 'Yılbaşı Dönemi', 'en' => 'New Year Season', 'ku' => 'Dema Sersalê'],
                'theme_type' => HeaderTheme::TYPE_RANGE,
                'starts_at' => '2026-12-20',
                'ends_at' => '2027-01-02',
                'priority' => 150,
                'banner_message' => ['tr' => 'Yeni yıl seçkisi', 'en' => 'New Year edit', 'ku' => 'Bijarteya Sersalê'],
                'headline' => ['tr' => 'Yeni yıl hediyeleri daha parlak bir vitrinde.', 'en' => 'New Year gifts in a brighter storefront.', 'ku' => 'Diyariyên Sersalê di vitrineke ronaktir de ne.'],
                'subline' => ['tr' => 'Sıcak ışıklar, kırmızı çiçekler ve butik çikolatalarla yılın son hediyesini unutulmaz kılın.', 'en' => 'Make the final gift of the year memorable with warm lights, red florals and boutique chocolates.', 'ku' => 'Bi ronahiyên germ, kulîlkên sor û çîkolatayên butik diyariya salê bîranînî bikin.'],
                'cta_label' => ['tr' => 'Keşfet', 'en' => 'Explore', 'ku' => 'Bibîne'],
                'special_occasion_slug' => 'yilbasi',
                'style_variant' => 'winter',
                'illustration_mode' => 'inline_svg',
                'illustration_asset' => 'winter',
                'decor_intensity' => 'soft',
            ],
        ];

        foreach ($themes as $theme) {
            HeaderTheme::query()->updateOrCreate(
                ['site' => HeaderTheme::SITE, 'slug' => $theme['slug']],
                array_merge([
                    'mode' => HeaderTheme::MODE_AUTOMATIC,
                    'is_enabled' => true,
                    'cta_url' => null,
                    'campaign_image' => null,
                ], $theme),
            );
        }
    }
}
